Weigh table panel feature
Maksim-Trolina/GraphVisualizer pull request #26
Opened 2020-10-17 23:41 UTC by EugenKoulik

2020-10-18 16:36 UTC, Maksim-Trolina commented on Forms/DrawForm/DrawForm.cs
> +                    matrixWeightPanel.CreateMatrix(1);
Name does not match functionality

2020-10-18 16:36 UTC, Maksim-Trolina commented on Forms/DrawForm/WeightTable.cs
> +            matrixx = new List<List<InputCountBox>>();
*matrix

2020-10-18 22:21 UTC, Maksim-Trolina approved these changes

2020-10-19 16:38 UTC, Maksim-Trolina requested changes
Make

2020-10-24 20:00 UTC, Maksim-Trolina approved these changes

2020-10-24 21:49 UTC, dnbss commented on Forms/DrawForm/DrawForm.cs
> +        private List<List<InputCountBox>> matrix;
Why do you create the "private List<List<Input Count Box>> matrix" field if it is not used anywhere except in the constructor, where it is only initialized?

2020-10-24 21:49 UTC, dnbss commented on Forms/DrawForm/WeightTable.cs
> +        public void DrawingMatrix(int rows)
Why do you pass a parameter here, if you have a "matrix" field that already contains information about the number of elements? This is not safe.

2020-10-24 23:07 UTC, dnbss approved these changes

2020-10-24 23:07 UTC, merged